export const queryKeys = {
  navbarCategoriesKey: ["navbarCategories"],
  conditionsInForm: ["conditionsInForm"],
  categoriesInForm: ["categoriesInForm"],
  collegesInForm: ["collegesInForm"],
  productsInDashboard: ["productsInDashboard"],
  noticesInDashboard: ["noticesInDashboard"],
  getProfile: ["getUserProfile"],
  getColleges: ["getColleges"],
  getAllProducts: ["getAllproducts"],
  singleProduct: ["singleProduct"],
  orders: ["orders"],
  purposesInForm: ["purposesInForm"],
  getAllNotices: ["getAllNotices"],
  sellerOrders: ["sellersOrders"],
};
