export const queryKeys = {
  navbarCategoriesKey: ["navbarCategories"],
  conditionsInForm: ["conditionsInForm"],
  categoriesInForm: ["categoriesInForm"],
  collegesInForm: ["collegesInForm"],
  productsInDashboard: ["productsInDashboard"],
  productLogs: ["productLogs"],
  noticesInDashboard: ["noticesInDashboard"],
  getProfile: ["getUserProfile"],
  getColleges: ["getColleges"],
  getAllProducts: ["getAllproducts"],
  singleProduct: ["singleProduct"],
  orders: ["orders"],
  singleOrder: ["singleOrder"],
  purposesInForm: ["purposesInForm"],
  getAllNotices: ["getAllNotices"],
  sellerOrders: ["sellersOrders"],
  chat: ["chat"],
  chats: ["chats"],
  buyerOrders: ["buyerOrders"],
  productPurposes: ["productPurposes"],
  rentProducts: ["rentProducts"],
  donatedProducts: ["donatedProducts"],
  transactions: ["transactios"],
  getAllAdsSliders: ["getAllAdsSliders"],
  getAllHeroSliders: ["getAllHeroSliders"],
  slidersInDashboard: ["slidersInDashboard"],
};
